services:
  app:
    build: .
    container_name: medisureos_app
    ports:
      - "5007:80"
    env_file:
      - .env
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://mediapp_user:Faith4tila@mediapp_db:5432/medisure_db
      # - API_KEY=your_gemini_api_key_here
    networks:
      - mediapp_mediapp_net
    restart: unless-stopped

networks:
  mediapp_mediapp_net:
    external: true
